# claude-pa configuration — annotated template.
#
# Installed location: $XDG_CONFIG_HOME/claude-pa/config.sh (defaults to
# ~/.config/claude-pa/config.sh). Generated by `pa init`; edited by hand
# afterwards. Sourced by lib/paths.sh on every `pa` invocation.
#
# IMPORTANT: this file IS sourced as bash. Only the wizard or you should ever
# write to it. Preset files in presets/<name>/config.env use a strict
# KEY=VALUE parser instead — never sourced — because they may come from
# third-party PRs (see CONTRIBUTING.md).
#
# All paths support ~ and $HOME expansion. Quote anything with spaces
# (iCloud paths in particular).

# ─── Required ───────────────────────────────────────────────────────────────

# Absolute path to your Obsidian-style vault root. Daily notes, projects,
# templates all live underneath. Must exist and be a directory.
PA_VAULT="$HOME/Obsidian/MyVault"

# Absolute path to the parent directory of your project repos. `pa spawn
# <repo>` cd's into $PA_PROJECTS_DIR/<repo> before launching claude.
PA_PROJECTS_DIR="$HOME/Projects"

# ─── Terminal backend ───────────────────────────────────────────────────────

# Which terminal abstraction to use. `auto` detects via $TMUX / $TERM_PROGRAM
# / $KITTY_WINDOW_ID and falls back to tmux. Pin explicitly if auto-detect
# misfires (e.g. running tmux inside WezTerm and you want WezTerm).
# Values: auto | wezterm | kitty | iterm2 | tmux
PA_TERMINAL_BACKEND="auto"

# ─── Pane / window naming ───────────────────────────────────────────────────

# Title of the orchestrator pane (the one running this skill). Backends mark
# it with terminal_set_title so peer panes can identify "home" for focus
# operations and to avoid killing it during EOD shutdown.
PA_MAIN_TITLE="MAIN"

# ─── Vault layout (Obsidian conventions) ────────────────────────────────────

# Subdirectory of $PA_VAULT holding daily notes named YYYY-MM-DD.md.
PA_DAILY_DIR="Daily"

# Path to the daily-note template, relative to $PA_VAULT. The morning
# routine copies this file, substitutes {{date}} placeholders, and writes
# today's daily note. Must exist.
PA_DAILY_TEMPLATE_PATH="_templates/Daily Note.md"

# Heading inside the daily-note template under which work tasks live.
# Carry-over moves unchecked tasks from this section forward each day.
PA_WORK_SECTION="Work"

# Same, for personal tasks. Set to the empty string to disable a personal
# section entirely.
PA_PERSONAL_SECTION="Personal"

# Subdirectory of $PA_VAULT holding feature notes. Feature notes are the
# unit of project tracking — one .md file per feature with a status:
# frontmatter property. Layout: $PA_VAULT/$PA_FEATURE_NOTE_DIR/<project>/<Feature Title>.md
PA_FEATURE_NOTE_DIR="PROJECTS"

# ─── Status taxonomy ────────────────────────────────────────────────────────

# Comma-separated list of valid values for a feature note's status:
# frontmatter property. Order suggests progression but is not enforced.
PA_STATUS_VALUES="brainstorming,planned,in-progress,shipped"

# The status value that causes the morning routine to tick the matching
# [[link]] in the prior day's daily note. Must appear in PA_STATUS_VALUES.
PA_STATUS_SHIPPED="shipped"

# ─── Spawn behavior ─────────────────────────────────────────────────────────

# Template injected into newly spawned project panes after the prompt
# arrives. Placeholders substituted at spawn time:
#   {title}    feature note title
#   {intent}   one-line intent passed to `pa spawn`
#   {context}  optional context block
#
# Empty string = no auto-injection; the pane opens to a bare claude prompt.
# Example for Compound Engineering users:
#   PA_SPAWN_PROMPT_TEMPLATE="/workflows:brainstorm {title} — {intent} | {context}"
PA_SPAWN_PROMPT_TEMPLATE=""

# ─── Dashboard ──────────────────────────────────────────────────────────────

# How often the live dashboard re-renders, in seconds. 2 matches the
# default of the prior internal PA tool. Lower = more responsive, higher
# CPU + flicker risk on slow terminals.
PA_DASHBOARD_INTERVAL="2"

# ─── Debug ──────────────────────────────────────────────────────────────────

# 1 = verbose logging to $XDG_DATA_HOME/claude-pa/logs/pa-YYYY-MM-DD.log.
# 0 = silent (default). `pa doctor --verbose` also prints diagnostics
# regardless of this flag.
PA_DEBUG="0"
